# Generated by Django 5.0.7 on 2024-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='num_chairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_tables',
            field=models.IntegerField(default=0),
        ),
    ]
