# Generated by Django 5.0.7 on 2024-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore')], max_length=10),
        ),
    ]
