# Generated by Django 5.0.7 on 2024-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_paymentmethod_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('QR', 'QR'), ('CREDIT', 'CREDIT')], max_length=10),
        ),
    ]
