# Generated by Django 5.0.7 on 2024-07-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_paymentmethod_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_categories',
            new_name='categories',
        ),
    ]
