# Generated by Django 5.0.7 on 2024-07-15 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_paymentmethod_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_in',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='order_item_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('QR', 'QR CODE'), ('CREDIT', 'CREDIT')]),
        ),
    ]
