# Generated by Django 5.0.7 on 2024-07-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_order_in_orderitem_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='paymentitem',
            old_name='order_item_id',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='paymentitem',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
